Add the empty graph
KatanaGraph/test-datasets pull request #3
Opened 2022-02-18 18:25 UTC by aneeshdurg

I think eventually it should be possible for csv-import to just create this graph, but until then, I was encouraged to drop this here.

2022-02-18 18:32 UTC, e-mcginnis requested changes
Please add a script to import this from an empty csv automatically for upreving the storage format version, doing this manually every time we bump the storage format version wastes a lot of time fast. 

 I can help you out with writing this is you'd like

EDIT: you can take a look at this import script for the smiles_small rdg https://github.com/KatanaGraph/test-datasets/blob/master/rdg_datasets/smiles_small/import.py

2022-02-18 18:32 UTC, e-mcginnis commented on rdg_datasets/empty_graph/storage_format_version_6/part_vers00000000000000000001_rdg_node00000
> +{"kg.v1.edge_entity_type_id_array":"edge_entity_type_id_array-fppqocT7GcMP","kg.v1.edge_entity_type_id_dictionary":[[0,[]]],"kg.v1.edge_entity_type_id_name":[],"kg.v1.edge_property":[],"kg.v1.node_en
this rdg is `kg.v1.storage_format_version":5`, please put it in a `storage_format_version_5` directory

apologies, v6 is just making its way into the codebase as we speak

2022-02-22 16:59 UTC, aneeshdurg commented
So I tried writing an import script, but it didn't seem to like importing from an empty file. Right now the only tool that really supports generating valid empty-graphs is csv-import. Maybe I can write a generate script instead?

2022-02-22 18:07 UTC, e-mcginnis commented
> Right now the only tool that really supports generating valid empty-graphs is csv-import

The backend of the import tooling is csv-import
https://github.com/KatanaGraph/test-datasets/blob/219aaa51568c45e4c9599a160ee2b95265b06310/libuprev/rdg_import.py#L49
so something else must be up.
If you want to share the code & error with me, I can take a look?

2022-03-11 20:30 UTC, e-mcginnis approved these changes

2022-03-11 20:52 UTC, merged